<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDFwdsWR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDFwdsWR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDFwdsWR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDFwdsWR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDFwdsWR\App_KernelDevDebugContainer([
    'container.build_hash' => 'DFwdsWR',
    'container.build_id' => 'a1957c00',
    'container.build_time' => 1590666857,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDFwdsWR');
